name: Greybus Module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Twister samples
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        path: greybus

    - name: Setup Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: greybus
        toolchains: arm-zephyr-eabi

    - name: Build
      env:
        MCUBOOT_PATH: twister-out/beagleconnect_freedom_cc1352p7/zephyr_gnu/greybus/samples/basic/sample.greybus.basic.transport.tcpip/mcuboot/zephyr/zephyr.bin
        SIGNED_PATH: twister-out/beagleconnect_freedom_cc1352p7/zephyr_gnu/greybus/samples/basic/sample.greybus.basic.transport.tcpip/basic/zephyr/zephyr.signed.bin
      run: |
        mkdir dist
        west twister -T greybus
        mv ${MCUBOOT_PATH} dist/beagleconnect_freedom_subg.bin
        dd conv=notrunc bs=1024 seek=56 if=${SIGNED_PATH} of=dist/beagleconnect_freedom_subg.bin
        xz -z dist/beagleconnect_freedom_subg.bin
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: greybus-beagleconnect-freedom
        path: |
          dist/*
